#!/bin/bash
# ----------------------------------------------------
# @author  icollar
# @version 2.0.1
# @title   grid
# @desc    Window positioning tool. Resizes and moves
#          the window in focus to the desired location
#          and size; in thirds, half two thirds.
# ----------------------------------------------------

WINDOW_ID=$(xdotool getactivewindow)

FRAME_H=$(xprop -id $WINDOW_ID | grep -Po 'FRAME.*=\s*\K.*' | awk -F, '{print $3}')
PANEL_H=$(wmctrl -lG | head -n 1| awk '/[pP]anel/{print $6}')

screens=0
for screen in $(xrandr | grep -Po '[^(dis)]connected[\sa-z]*\K\d+x\d+\+\d+')
do
	screens=$((screens+1))
	if [ $(echo $screen | awk -F[x+] '{print $3}') -gt 0 ];then
		DISPLAY_RW=$(echo $screen | awk -F[x+] '{print $1}')
		DISPLAY_RH=$(echo $screen | awk -F[x+] '{print $2}')
	else
		DISPLAY_LW=$(echo $screen | awk -F[x+] '{print $1}')
		DISPLAY_LH=$(echo $screen | awk -F[x+] '{print $2}')
	fi
done

CURRENT_W=$(xwininfo -id $WINDOW_ID | awk '/Width:/{print $NF}')
CURRENT_X=$(xwininfo -id $WINDOW_ID | awk '/Absolute.*X:/{print $NF}')

if [[ "$CURRENT_X" -lt "$DISPLAY_LW" ]]; then
	DISPLAY_W=$DISPLAY_LW
	DISPLAY_H=$DISPLAY_LH
	X=0
else
	DISPLAY_W=$DISPLAY_RW
	DISPLAY_H=$DISPLAY_RH
	X=$DISPLAY_LW
fi


W13=$((DISPLAY_W/3))
W12=$((DISPLAY_W/2))
W23=$((DISPLAY_W/3*2))


function move-left () {
	if [ $screens -gt 1 -a $CURRENT_X -ge $DISPLAY_LW ]; then
		H=-1
		Y=-1
		W=-1
		X=$((CURRENT_X - $DISPLAY_RW))
	else
		exit 1
	fi
}
function move-right () {
	if [ $screens -gt 1 -a $CURRENT_X -lt $DISPLAY_LW ]; then
		H=-1
		Y=-1
		W=-1
		X=$((CURRENT_X + $DISPLAY_LW))
	else
		exit 1
	fi
}

function width () {
	if [ $CURRENT_W -gt $W23 ]; then
		W=$W23
	elif [ $CURRENT_W -ge $((W23-5)) ]; then
		W=$W12
	elif [ $CURRENT_W -ge $((W12-5)) ]; then
		W=$W13
	else
		W=$W23
	fi
}

function bottom () {
	Y=$(((DISPLAY_H - PANEL_H) / 2 + FRAME_H))
}

function half-height () {
	H=$(((DISPLAY_H - PANEL_H) / 2 - FRAME_H))
}

function right-x () {
	X=$((X + DISPLAY_W - W))
}

function left () {
	wmctrl -ir $WINDOW_ID -b remove,maximized_horz
	wmctrl -ir $WINDOW_ID -b add,maximized_vert
	width
	Y=0
	H=-1
}

function right () {
	wmctrl -ir $WINDOW_ID -b remove,maximized_horz
	wmctrl -ir $WINDOW_ID -b add,maximized_vert
	width
	Y=0
	H=-1
	right-x
}

function middle () {
	wmctrl -ir $WINDOW_ID -b remove,maximized_horz
	wmctrl -ir $WINDOW_ID -b add,maximized_vert
	W=$W13
	Y=0
	H=-1
	X=$((X + W13))
}

function top-middle () {
	wmctrl -ir $WINDOW_ID -b remove,maximized_vert
	wmctrl -ir $WINDOW_ID -b toggle,maximized_horz
	W=$W13
	Y=0
	half-height
	X=$((X + W13))
}


function top-left () {
	wmctrl -ir $WINDOW_ID -b remove,maximized_vert,maximized_horz
	width
	Y=0
	half-height
}

function top-right () {
	wmctrl -ir $WINDOW_ID -b remove,maximized_vert,maximized_horz
	width
	Y=0
	H=$(((DISPLAY_H - PANEL_H) / 2))
	right-x
}

function bottom-left () {
	wmctrl -ir $WINDOW_ID -b remove,maximized_vert,maximized_horz
	width
	half-height
	bottom
}

function bottom-right () {
	wmctrl -ir $WINDOW_ID -b remove,maximized_vert,maximized_horz
	width
	half-height
	bottom
	right-x
}

function bottom-middle () {
	wmctrl -ir $WINDOW_ID -b remove,maximized_vert
	wmctrl -ir $WINDOW_ID -b toggle,maximized_horz
	W=$W13
	half-height
	X=$((X + W13))
	bottom
}


function sticky () {
	wmctrl -ir $WINDOW_ID -b toggle,sticky
	exit 1
}

function above () {
	wmctrl -ir $WINDOW_ID -b toggle,above
	exit 1
}

function tiny () {
	wmctrl -ir $WINDOW_ID -b remove,maximized_vert,maximized_horz,above
	wmctrl -ir $WINDOW_ID -b add,above
	top-right
	H=80
}



case $1 in
	--move-left)     move-left;;
	--move-right)    move-right;;
	--left)          left;;
	--right)         right;;
	--middle)        middle;;
	--top-left)      top-left;;
	--top-right)     top-right;;
	--top-middle)    top-middle;;
	--bottom-left)   bottom-left;;
	--bottom-right)  bottom-right;;
	--bottom-middle) bottom-middle;;
	--sticky)        sticky;;
	--above)         above;;
	--tiny)          tiny;;
	*) exit 1;;
esac


wmctrl -ir $WINDOW_ID -e 0,$X,$Y,$W,$H
sleep 0.1
wmctrl -ir $WINDOW_ID -e 0,$X,$Y,$W,$H
