#!/bin/bash
# ----------------------------------------------------
# @author  icollar
# @version 0.0.1
# @title   direction-switch
# @desc    Window switching tool. Focus switches to
#          the next window in the desired direction.
# ----------------------------------------------------

if [ -z "$1" ]; then
	echo "No search term provided...";
	exit 1;
fi;
if [ -z "$2" ]; then
	loc=.
else
	loc=$2
fi;

echo "grep ${GREP_OPT} \"$1\" $loc";
grep ${GREP_OPT} "$1" $loc |
	perl -ne 's/\.\/(.*):([0-9]+):\s*(.*)/printf("\e[35mvi%6s %-80s  \e[m--  %s\n","+$2",$1,$3,$5)/ei' | perl -pe "s/($1)/\e[31m\1\e[m/gi" |
	less -RS

